# Generated by Django 5.1.3 on 2025-02-19 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_admin',
            old_name='pswd',
            new_name='password',
        ),
    ]
