# Generated by Django 5.1.3 on 2025-02-20 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
