# Generated by Django 5.1.3 on 2025-02-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
