# Generated by Django 5.1.3 on 2025-03-11 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('card_holder_name', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=16)),
                ('expiry_date', models.CharField(max_length=7)),
                ('cvv', models.CharField(max_length=4)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='userapp.productbookings')),
            ],
        ),
        migrations.CreateModel(
            name='Upi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='success', max_length=20)),
                ('upi_id', models.CharField(max_length=100)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upi', to='userapp.productbookings')),
            ],
        ),
    ]
